# Generated by Django 5.2.6 on 2025-10-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemAlugados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluguel",
            name="dias",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
