# Generated by Django 5.2.6 on 2025-09-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('descricao', models.TextField(max_length=200)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('investimento', 'Investimento')], max_length=50)),
            ],
        ),
    ]
