# Generated by Django 5.2.6 on 2025-11-10 00:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_transacao", models.DateField(default=datetime.date.today)),
                ("recorrente", models.BooleanField(default=False)),
                ("descricao", models.TextField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("receita", "Receita"),
                            ("despesa", "Despesa"),
                            ("investimento", "Investimento"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
