# Generated by Django 5.2.6 on 2025-09-22 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_transacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='item',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
