# Generated by Django 5.2.6 on 2025-11-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_item_data_transacao_item_recorrente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
