# Generated by Django 5.2.6 on 2025-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_item_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
