# Generated by Django 5.2.6 on 2025-11-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_evento", models.DateField()),
                ("horario_inicio", models.TimeField(blank=True, null=True)),
                ("horario_fim", models.TimeField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda",
                "verbose_name_plural": "Agendas",
                "ordering": ["data_evento", "horario_inicio"],
            },
        ),
    ]
