# Generated by Django 5.2.6 on 2025-10-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item_aluguel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("quantidade_total", models.PositiveSmallIntegerField()),
                ("diaria", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
